### ISSUE TITLE
Can't create race track

### ISSUE THREAD

**Issue by SavageBRG** [npwd-community/npwd-qb-racing#3]
![image](https://user-images.githubusercontent.com/100693965/187144773-9c81d994-69d4-4ce2-8bba-e336d5c165da.png)
I am using NPWD 1.5.3 and npwd-qb-racing 0.0.1-4-alpha. When I go to create a race track I get a Syntax Error (the one in the picture). I am also using the latest qb-lapraces and had lapraces working correctly with the normal qb-phone (Lapraces config setup correctly) 

This is all the information I think I can give. I am happy to give any more if you need or have more questions.

**Comment by CptNoHand** [comment]
same

**Comment by antonstjernquist** [comment]
Are you using latest qb-lapraces? It got updated.

**Comment by antonstjernquist** [comment]
https://github.com/npwd-community/npwd_qb_racing/releases/tag/0.0.5
