### ISSUE TITLE
Tracks issue

### ISSUE THREAD

**Issue by parham-tehrani** [npwd-community/npwd-qb-racing#4]
i know i have 10+ races on the old phone.
1-is there a way to import tracks?
2-can't create races.

**Comment by VoyaCoz** [comment]
> i know i have 10+ races on the old phone. 1-is there a way to import tracks? 2-can't create races.

same can't do anything about it

**Comment by antonstjernquist** [comment]
Old tracks should show up

**Comment by antonstjernquist** [comment]
https://github.com/npwd-community/npwd_qb_racing/releases/tag/0.0.5
