### ISSUE TITLE
[BUILD ERROR] Not outputting the correct files

### ISSUE THREAD

**Issue by 123B3n** [npwd-community/npwd-qb-racing#5]
So, all I've figured out so far is that the release here on github does not output the `dist` folder and it's contenct which is loaded by the `fxmanifest.lua` rendering this plugin completely useless.

I've tried myself to rebuild it in yarn and all of that, however, that only makes the app into an loading state and nothing else happens. Unclear why since I've never really used yarn before. But all the releases has no NUI Callbacks which is causing people to not be able to create any races and so on.

All that is needed is the built dist files to make it work properly again.

**Comment by antonstjernquist** [comment]
Thanks, this is the root cause of everything

**Comment by antonstjernquist** [comment]
https://github.com/npwd-community/npwd_qb_racing/releases/tag/0.0.5
